// export { Admins } from './admin-model';
export { Brand } from './brand-model';
export { Category } from './category-model';
export { Client } from './client-model';
export { Merchant } from './merchant-model';
export { Models } from './model-model';
export { OTP } from './otp-model';
export { Products } from './product-model';
export { Users } from './users-model';
export { Widgets } from './widgets-model';
